[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@ensdomains/=./../node_modules/@ensdomains/",
    "@ethereum-waffle/=./../node_modules/@ethereum-waffle/",
    "@openzeppelin/=./../node_modules/@openzeppelin/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "eth-gas-reporter/=./../node_modules/eth-gas-reporter/",
    "hardhat/=./../node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
